Repository next-work-team/Auctify-server, pull requests merged in 2025-05, with the labels that each got.

#106 [Chore]SSE관련 임시 Swagger문서 수정
  src/main/java/org/example/auctify/controller/user/UserController.java
  src/main/java/org/example/auctify/controller/user/UserControllerDocs.java
Labels: documentation

#108 [Feat]myBidAPI재구현
  src/main/java/org/example/auctify/controller/auction/GoodsController.java
  src/main/java/org/example/auctify/controller/auction/GoodsControllerDocs.java
  src/main/java/org/example/auctify/controller/user/UserController.java
  src/main/java/org/example/auctify/controller/user/UserControllerDocs.java
  src/main/java/org/example/auctify/repository/bidHistory/BidHistoryRepositoryImpl.java
Labels: feat

#110 [fix] sse 구독 api 분리
  src/main/java/org/example/auctify/config/security/SecurityConfig.java
  src/main/java/org/example/auctify/controller/sse/SSEController.java
  src/main/java/org/example/auctify/controller/sse/SSEControllerDocs.java
  src/main/java/org/example/auctify/service/notification/NotificationService.java
  src/main/java/org/example/auctify/service/sse/SSEService.java
Labels: bug

#112 [fix] 채팅 응답 형식 수정
  build.gradle
  src/main/java/org/example/auctify/config/chat/WebSocketConfig.java
  src/main/java/org/example/auctify/controller/chat/ChatMessageController.java
  src/main/java/org/example/auctify/controller/chat/ChatRoomController.java
  src/main/java/org/example/auctify/controller/chat/ChatRoomControllerDocs.java
  src/main/java/org/example/auctify/dto/chat/AuctionDto.java
  src/main/java/org/example/auctify/dto/chat/EnterMessageDto.java
  src/main/java/org/example/auctify/dto/chat/GetMessageHistoryResDto.java
  src/main/java/org/example/auctify/dto/chat/GetOneToOneChatRoomListResDto.java
  src/main/java/org/example/auctify/dto/chat/LastMessageDto.java
  src/main/java/org/example/auctify/dto/chat/MessageDto.java
  src/main/java/org/example/auctify/dto/chat/UserDto.java
  src/main/java/org/example/auctify/entity/chat/ChatMessageEntity.java
  src/main/java/org/example/auctify/entity/chat/RedisChatRoomEntity.java
  src/main/java/org/example/auctify/repository/chat/ChatMessageRepository.java
  src/main/java/org/example/auctify/repository/chat/ConnectedChatUserRepository.java
  src/main/java/org/example/auctify/repository/chat/CustomChatMessageRepository.java
  src/main/java/org/example/auctify/repository/chat/CustomChatMessageRepositoryImpl.java
  src/main/java/org/example/auctify/repository/chat/UserChatRoomRepository.java
  src/main/java/org/example/auctify/service/chat/ChatMessageService.java
  src/main/java/org/example/auctify/service/chat/ChatRoomService.java
  src/main/java/org/example/auctify/service/chat/SendEnterMessage.java
  src/main/java/org/example/auctify/util/websocket/StompHandler.java
Labels: bug

#113 [fix] 입찰 내역 정렬 수정
  src/main/java/org/example/auctify/repository/bidHistory/BidHistoryRepository.java
  src/main/java/org/example/auctify/service/notification/NotificationService.java
Labels: bug

#114 [fix] 알림 응답 수정
  src/main/java/org/example/auctify/dto/notification/NotificationListResDto.java
  src/main/java/org/example/auctify/entity/notification/NotificationEntity.java
  src/main/java/org/example/auctify/service/notification/NotificationService.java
Labels: bug

#115 [fix] SSE 실시간 입찰 데이터 전송 응답 수정
  src/main/java/org/example/auctify/dto/notification/AuctionSummaryDTO.java
  src/main/java/org/example/auctify/dto/notification/BidHistoryDTO.java
  src/main/java/org/example/auctify/dto/notification/BidUpdateResDTO.java
  src/main/java/org/example/auctify/service/notification/NotificationService.java
Labels: bug
