Repository next-work-team/Auctify-server, pull requests merged in 2025-03, with the labels that each got.

#19 [Fix] cors에러수정
  src/main/java/org/example/auctify/config/CorsMvcConfig.java
  src/main/java/org/example/auctify/config/SecurityConfig.java
  src/main/java/org/example/auctify/oauth2/CustomSuccessHandler.java
Labels: bug

#21 [Fix]토큰,cors에러수정
  src/main/java/org/example/auctify/config/CorsMvcConfig.java
  src/main/java/org/example/auctify/config/SecurityConfig.java
  src/main/java/org/example/auctify/oauth2/CustomSuccessHandler.java
Labels: bug

#24 [Feat] UserControllerSwagger구현
  src/main/java/org/example/auctify/controller/user/UserController.java
  src/main/java/org/example/auctify/controller/user/UserControllerDocs.java
  src/main/java/org/example/auctify/dto/user/ProfileDTO.java
Labels: feat

#25 [Feat]UserDetails인증정보가져오기
  src/main/java/org/example/auctify/config/security/CustomUserDetails.java
  src/main/java/org/example/auctify/config/security/SecurityConfig.java
  src/main/java/org/example/auctify/config/security/s3/S3Config.java
  src/main/java/org/example/auctify/controller/oauth2/MyController.java
  src/main/java/org/example/auctify/dto/social/GoogleResponse.java
  src/main/java/org/example/auctify/dto/social/KakaoResponse.java
  src/main/java/org/example/auctify/entity/user/UserEntity.java
  src/main/java/org/example/auctify/service/user/CustomOAuth2UserService.java
  src/main/java/org/example/auctify/service/user/CustomUserDetailsService.java
Labels: feat

#28 [Feat]user swagger 반환 dto 작성
  src/main/java/org/example/auctify/controller/user/UserController.java
  src/main/java/org/example/auctify/controller/user/UserControllerDocs.java
  src/main/java/org/example/auctify/dto/Goods/AuctionGoodsDTO.java
  src/main/java/org/example/auctify/dto/Goods/FeedbackDTO.java
  src/main/java/org/example/auctify/dto/Goods/GoodsStatus.java
  src/main/java/org/example/auctify/dto/social/UserDTO.java
  src/main/java/org/example/auctify/dto/user/AddressDTO.java
  src/main/java/org/example/auctify/dto/user/MannerTemperatureDTO.java
  src/main/java/org/example/auctify/dto/user/ProfileDTO.java
  src/main/java/org/example/auctify/dto/user/RequestUserDTO.java
  src/main/java/org/example/auctify/dto/user/UserInfoDTO.java
  src/main/java/org/example/auctify/entity/Goods/GoodsEntity.java
  src/main/java/org/example/auctify/oauth2/CustomSuccessHandler.java
Labels: feat

#31 [Modify] UserSwagger 수정
  src/main/java/org/example/auctify/controller/auction/GoodsControllerDocs.java
  src/main/java/org/example/auctify/controller/user/UserController.java
  src/main/java/org/example/auctify/controller/user/UserControllerDocs.java
  src/main/java/org/example/auctify/dto/Goods/AuctionGoodsDTO.java
  src/main/java/org/example/auctify/dto/Goods/FeedbackDTO.java
  src/main/java/org/example/auctify/dto/user/MannerTemperatureDTO.java
  src/main/java/org/example/auctify/dto/user/UserInfoRequestDTO.java
  src/main/java/org/example/auctify/dto/user/UserInfoResponseDTO.java
Labels: feat

#32 [Feat]auctionSwagger구현
  src/main/java/org/example/auctify/controller/auction/GoodsControllerDocs.java
  src/main/java/org/example/auctify/controller/auction/Goodscontroller.java
  src/main/java/org/example/auctify/controller/user/UserController.java
  src/main/java/org/example/auctify/controller/user/UserControllerDocs.java
  src/main/java/org/example/auctify/dto/Goods/AuctionResponseGoodsDTO.java
  src/main/java/org/example/auctify/dto/Goods/BidPurchaseRequestDTO.java
  src/main/java/org/example/auctify/dto/Goods/BidPurchaseResponseDTO.java
  src/main/java/org/example/auctify/dto/Goods/BidRequestDTO.java
  src/main/java/org/example/auctify/dto/Goods/BidResponseDTO.java
  src/main/java/org/example/auctify/dto/Goods/GoodsRequestDTO.java
  src/main/java/org/example/auctify/dto/Goods/LikeRequestDTO.java
  src/main/java/org/example/auctify/dto/Goods/LikeResponseDTO.java
  src/main/java/org/example/auctify/dto/Goods/ReviewRequestDTO.java
  src/main/java/org/example/auctify/dto/Goods/ReviewResponseDTO.java
  src/main/java/org/example/auctify/dto/Goods/SearchDTO.java
Labels: feat

#34 [Feat] 스웨거 get요청시 파라미터로 수정
  src/main/java/org/example/auctify/controller/auction/GoodsControllerDocs.java
  src/main/java/org/example/auctify/controller/auction/Goodscontroller.java
Labels: feat

#36 [Feature] entity create
  src/main/java/org/example/auctify/entity/bidHistory/BidHistoryEntity.java
  src/main/java/org/example/auctify/entity/like/LikeEntity.java
  src/main/java/org/example/auctify/entity/payment/PaymentEntity.java
  src/main/java/org/example/auctify/entity/review/ReviewEntity.java
Labels: feat

#37 [Feature] entity create
  src/main/java/org/example/auctify/AuctifyApplication.java
  src/main/java/org/example/auctify/controller/auction/GoodsControllerDocs.java
  src/main/java/org/example/auctify/dto/user/AddressDTO.java
  src/main/java/org/example/auctify/entity/Goods/GoodsCategoryEntity.java
  src/main/java/org/example/auctify/entity/Goods/GoodsEntity.java
  src/main/java/org/example/auctify/entity/Goods/GoodsImageEntity.java
  src/main/java/org/example/auctify/entity/bidHistory/BidHistoryEntity.java
  src/main/java/org/example/auctify/entity/like/LikeEntity.java
  src/main/java/org/example/auctify/entity/payment/PaymentEntity.java
  src/main/java/org/example/auctify/entity/review/ReviewEntity.java
  src/main/java/org/example/auctify/entity/user/AddressEntity.java
  src/main/java/org/example/auctify/entity/user/UserEntity.java
Labels: feat

#39 [Feat]Profile조회API구현
  src/main/java/org/example/auctify/config/security/CustomUserDetails.java
  src/main/java/org/example/auctify/controller/auction/GoodsControllerDocs.java
  src/main/java/org/example/auctify/controller/auction/Goodscontroller.java
  src/main/java/org/example/auctify/controller/oauth2/MyController.java
  src/main/java/org/example/auctify/controller/user/UserController.java
  src/main/java/org/example/auctify/controller/user/UserControllerDocs.java
  src/main/java/org/example/auctify/dto/social/CustomOauth2User.java
  src/main/java/org/example/auctify/dto/social/UserDTO.java
  src/main/java/org/example/auctify/dto/user/UserInfoResponseDTO.java
  src/main/java/org/example/auctify/entity/user/UserEntity.java
  src/main/java/org/example/auctify/jwt/JWTFilter.java
  src/main/java/org/example/auctify/jwt/JWTUtil.java
  src/main/java/org/example/auctify/oauth2/CustomSuccessHandler.java
  src/main/java/org/example/auctify/repository/bidHistory/BidHistoryRepository.java
  src/main/java/org/example/auctify/repository/goods/GoodsCategoryRepository.java
  src/main/java/org/example/auctify/repository/goods/GoodsImageRepository.java
  src/main/java/org/example/auctify/repository/goods/GoodsRepository.java
  src/main/java/org/example/auctify/repository/like/LikeRepository.java
  src/main/java/org/example/auctify/repository/payment/PaymentRepository.java
  src/main/java/org/example/auctify/repository/review/ReviewRepository.java
  src/main/java/org/example/auctify/repository/user/AddressRepository.java
  src/main/java/org/example/auctify/repository/user/UserRepository.java
  src/main/java/org/example/auctify/service/user/CustomOAuth2UserService.java
  src/main/java/org/example/auctify/service/user/UserService.java
Labels: feat

#44 [Chore]ApiResponseDTO적용
  src/main/java/org/example/auctify/controller/auction/GoodsControllerDocs.java
  src/main/java/org/example/auctify/controller/auction/Goodscontroller.java
Labels: feat

#46 [Freature]DuplicationCheck기능추가
  src/main/java/org/example/auctify/controller/auction/Goodscontroller.java
  src/main/java/org/example/auctify/controller/user/UserController.java
  src/main/java/org/example/auctify/controller/user/UserControllerDocs.java
  src/main/java/org/example/auctify/dto/duplication/DuplicationDTO.java
  src/main/java/org/example/auctify/dto/user/UserChangedProfileResponseDTO.java
  src/main/java/org/example/auctify/dto/user/UserInfoRequestDTO.java
  src/main/java/org/example/auctify/repository/user/UserRepository.java
  src/main/java/org/example/auctify/service/user/UserService.java
Labels: feat

#48 [Feature]GoodsAPI구현
  .gitignore
  build.gradle
  src/main/java/org/example/auctify/config/querydsl/QueryDslConfig.java
  src/main/java/org/example/auctify/controller/auction/GoodsController.java
  src/main/java/org/example/auctify/controller/auction/GoodsControllerDocs.java
  src/main/java/org/example/auctify/controller/auction/Goodscontroller.java
  src/main/java/org/example/auctify/dto/Goods/AuctionResponseGoodsDTO.java
  src/main/java/org/example/auctify/dto/Goods/GoodsCategory.java
  src/main/java/org/example/auctify/dto/Goods/GoodsProcessStatus.java
  src/main/java/org/example/auctify/dto/Goods/GoodsRequestDTO.java
  src/main/java/org/example/auctify/dto/Goods/GoodsResponseDTO.java
  src/main/java/org/example/auctify/dto/Goods/GoodsResponseSummaryDTO.java
  src/main/java/org/example/auctify/dto/Goods/GoodsStatus.java
  src/main/java/org/example/auctify/dto/Goods/ReviewRequestDTO.java
  src/main/java/org/example/auctify/dto/bid/BidHistoryResponseDTO.java
  src/main/java/org/example/auctify/entity/Goods/GoodsCategoryEntity.java
  src/main/java/org/example/auctify/entity/Goods/GoodsEntity.java
  src/main/java/org/example/auctify/entity/bidHistory/BidHistoryEntity.java
  src/main/java/org/example/auctify/entity/like/LikeEntity.java
  src/main/java/org/example/auctify/repository/bidHistory/BidHistoryRepository.java
  src/main/java/org/example/auctify/repository/goods/GoodsCategoryRepository.java
  src/main/java/org/example/auctify/repository/goods/GoodsRepository.java
  src/main/java/org/example/auctify/repository/goods/GoodsRepositoryCustom.java
  src/main/java/org/example/auctify/repository/goods/GoodsRepositoryCustomImpl.java
  src/main/java/org/example/auctify/repository/like/LikeRepository.java
  src/main/java/org/example/auctify/repository/review/ReviewRepository.java
  src/main/java/org/example/auctify/service/auction/GoodsService.java
  src/main/java/org/example/auctify/service/user/UserService.java
Labels: feat

#51 [Fix]소셜로그인후권한에러수정
  src/main/java/org/example/auctify/config/security/CustomUserDetails.java
  src/main/java/org/example/auctify/config/security/SecurityConfig.java
  src/main/java/org/example/auctify/dto/social/CustomOauth2User.java
  src/main/java/org/example/auctify/jwt/JWTFilter.java
Labels: bug

#52 [Chore]찜목록전달데이터수정
  src/main/java/org/example/auctify/dto/like/LikeGoodsResponseDTO.java
  src/main/java/org/example/auctify/service/user/UserService.java
Labels: feat

#54 [Feature]채팅 툴 설정
  .gitignore
  build.gradle
  src/main/java/org/example/auctify/config/chat/WebSocketConfig.java
  src/main/java/org/example/auctify/util/websocket/StompHandler.java
Labels: enhancement
