Repository next-work-team/Auctify-server, pull requests merged in 2025-04, with the labels that each got.

#55 [Feature]결제API구현
  build.gradle
  src/main/java/org/example/auctify/config/CorsMvcConfig.java
  src/main/java/org/example/auctify/config/querydsl/QueryDslConfig.java
  src/main/java/org/example/auctify/config/security/CustomUserDetails.java
  src/main/java/org/example/auctify/config/security/SecurityConfig.java
  src/main/java/org/example/auctify/controller/tossPayments/PaymentController.java
  src/main/java/org/example/auctify/dto/tossPayments/PayRequestDTO.java
  src/main/java/org/example/auctify/dto/tossPayments/PaymentResponseDTO.java
  src/main/java/org/example/auctify/dto/tossPayments/TossPaymentsResponseDTO.java
  src/main/java/org/example/auctify/entity/payment/PaymentEntity.java
  src/main/java/org/example/auctify/oauth2/CustomSuccessHandler.java
  src/main/java/org/example/auctify/service/payment/PaymentService.java
Labels: feat

#58 [Chore]결제Swagger수정
  src/main/java/org/example/auctify/controller/tossPayments/PaymentController.java
  src/main/java/org/example/auctify/controller/tossPayments/PaymentInterface.java
  src/main/java/org/example/auctify/dto/tossPayments/PayRequestDTO.java
Labels: feat

#60 [Chore]URL권한설정수정
  src/main/java/org/example/auctify/config/security/SecurityConfig.java
  src/main/java/org/example/auctify/service/auction/GoodsService.java
Labels: feat

#62 [Feature]요약입찰내역API구현
  src/main/java/org/example/auctify/config/security/SecurityConfig.java
  src/main/java/org/example/auctify/controller/auction/GoodsController.java
  src/main/java/org/example/auctify/controller/auction/GoodsControllerDocs.java
  src/main/java/org/example/auctify/dto/bid/BidSummaryDTO.java
  src/main/java/org/example/auctify/repository/goods/GoodsRepository.java
  src/main/java/org/example/auctify/service/auction/GoodsService.java
Labels: feat

#68 [Freature]스케줄러기능구현
  src/main/java/org/example/auctify/scheduler/AuctifyScheduledTask.java
Labels: feat

#69 Feat/1대1채팅
  .gitignore
  Dockerfile
  build.gradle
  src/main/java/org/example/auctify/config/chat/WebSocketConfig.java
  src/main/java/org/example/auctify/controller/chat/ChatMessageController.java
  src/main/java/org/example/auctify/controller/chat/ChatRoomController.java
  src/main/java/org/example/auctify/dto/chat/ChatRoomStatus.java
  src/main/java/org/example/auctify/dto/chat/CreateOneToOneChatReqDto.java
  src/main/java/org/example/auctify/dto/chat/GetMessageHistoryResDto.java
  src/main/java/org/example/auctify/dto/chat/GetOneToOneChatRoomListResDto.java
  src/main/java/org/example/auctify/dto/chat/MessageDto.java
  src/main/java/org/example/auctify/dto/chat/UserChatRoomStatus.java
  src/main/java/org/example/auctify/entity/chat/ChatMessageEntity.java
  src/main/java/org/example/auctify/entity/chat/ChatRoomEntity.java
  src/main/java/org/example/auctify/entity/chat/UserChatRoomEntity.java
  src/main/java/org/example/auctify/repository/chat/ChatMessageRepository.java
  src/main/java/org/example/auctify/repository/chat/ChatRoomRepository.java
  src/main/java/org/example/auctify/repository/chat/UserChatRoomRepository.java
  src/main/java/org/example/auctify/service/chat/ChatMessageService.java
  src/main/java/org/example/auctify/service/chat/ChatRoomService.java
  src/main/java/org/example/auctify/service/chat/MessageSender.java
Labels: enhancement

#70 Feat/스케줄러기능구현
  src/main/java/org/example/auctify/AuctifyApplication.java
  src/main/java/org/example/auctify/entity/Goods/GoodsEntity.java
  src/main/java/org/example/auctify/repository/goods/GoodsRepository.java
  src/main/java/org/example/auctify/scheduler/AuctifyScheduledTask.java
  src/main/java/org/example/auctify/service/auction/GoodsService.java
Labels: feat

#71 [Feature]입찰시경매상태체크
  src/main/java/org/example/auctify/entity/Goods/GoodsEntity.java
  src/main/java/org/example/auctify/service/auction/GoodsService.java
Labels: feat

#75 [Fix]인증오류수정
  src/main/java/org/example/auctify/config/security/JwtTokenProvider.java
  src/main/java/org/example/auctify/config/security/SecurityConfig.java
  src/main/java/org/example/auctify/controller/user/UserController.java
  src/main/java/org/example/auctify/dto/social/CustomOauth2User.java
  src/main/java/org/example/auctify/dto/user/Role.java
  src/main/java/org/example/auctify/jwt/JWTFilter.java
  src/main/java/org/example/auctify/oauth2/CustomSuccessHandler.java
  src/main/java/org/example/auctify/service/user/CustomOAuth2UserService.java
Labels: bug

#77 [Feat]로그인유저정보전달
  src/main/java/org/example/auctify/controller/oauth2/MyController.java
  src/main/java/org/example/auctify/dto/response/ApiResponseDTO.java
  src/main/resources/application.yml
Labels: feat

#80 [Fix]마이프로필수정API
  src/main/java/org/example/auctify/config/CorsMvcConfig.java
  src/main/java/org/example/auctify/config/security/SecurityConfig.java
  src/main/java/org/example/auctify/controller/user/UserController.java
  src/main/java/org/example/auctify/controller/user/UserControllerDocs.java
  src/main/java/org/example/auctify/entity/user/UserEntity.java
  src/main/java/org/example/auctify/oauth2/CustomSuccessHandler.java
  src/main/java/org/example/auctify/repository/user/UserRepository.java
  src/main/java/org/example/auctify/service/user/UserService.java
Labels: bug

#84 [Feature] 알림 API 구현
  src/main/java/org/example/auctify/config/chat/WebSocketConfig.java
  src/main/java/org/example/auctify/controller/auction/GoodsController.java
  src/main/java/org/example/auctify/controller/chat/ChatMessageController.java
  src/main/java/org/example/auctify/controller/notification/NotificationController.java
  src/main/java/org/example/auctify/dto/chat/JoinRoomDto.java
  src/main/java/org/example/auctify/dto/chat/LeaveRoomDto.java
  src/main/java/org/example/auctify/dto/chat/MessageDto.java
  src/main/java/org/example/auctify/dto/notification/ChatNotificationDto.java
  src/main/java/org/example/auctify/dto/notification/NotificationType.java
  src/main/java/org/example/auctify/entity/notification/NotificationEntity.java
  src/main/java/org/example/auctify/repository/bidHistory/BidHistoryRepository.java
  src/main/java/org/example/auctify/repository/goods/GoodsRepository.java
  src/main/java/org/example/auctify/repository/notification/NotificationRepository.java
  src/main/java/org/example/auctify/scheduler/AuctifyScheduledTask.java
  src/main/java/org/example/auctify/service/auction/GoodsService.java
  src/main/java/org/example/auctify/service/chat/ChatMessageService.java
  src/main/java/org/example/auctify/service/chat/UserSessionService.java
  src/main/java/org/example/auctify/service/notification/NotificationSender.java
  src/main/java/org/example/auctify/service/notification/NotificationService.java
  src/main/java/org/example/auctify/util/websocket/StompHandler.java
Labels: enhancement

#86 [Fix]유저컨트럴조회로직수정
  .github/workflows/deploy.yml
  src/main/java/org/example/auctify/entity/Goods/GoodsEntity.java
  src/main/java/org/example/auctify/repository/bidHistory/BidHistoryRepository.java
  src/main/java/org/example/auctify/repository/goods/GoodsRepository.java
  src/main/java/org/example/auctify/service/auction/GoodsService.java
Labels: bug

#88 [Fix]경매컨트럴러조회로직수정
  src/main/java/org/example/auctify/controller/auction/GoodsController.java
  src/main/java/org/example/auctify/repository/goods/GoodsRepositoryCustomImpl.java
Labels: bug

#90 [Fix]경매C,U,D관련API수정
  src/main/java/org/example/auctify/controller/auction/GoodsController.java
  src/main/java/org/example/auctify/controller/auction/GoodsControllerDocs.java
  src/main/java/org/example/auctify/repository/goods/GoodsRepository.java
  src/main/java/org/example/auctify/service/auction/GoodsService.java
Labels: bug

#91 [Feature] 알림 목록 조회 기능 구현
  src/main/java/org/example/auctify/controller/notification/NotificationController.java
  src/main/java/org/example/auctify/dto/notification/NotificationListResDto.java
  src/main/java/org/example/auctify/dto/notification/NotificationType.java
  src/main/java/org/example/auctify/repository/notification/NotificationRepository.java
  src/main/java/org/example/auctify/service/notification/NotificationService.java
Labels: enhancement

#93 [Feature]PresignedURLDELETE구현CORS설정
  src/main/java/org/example/auctify/config/CorsMvcConfig.java
  src/main/java/org/example/auctify/config/security/SecurityConfig.java
  src/main/java/org/example/auctify/controller/presigned/PresignedController.java
  src/main/java/org/example/auctify/controller/presigned/PresignedControllerDocs.java
  src/main/java/org/example/auctify/dto/s3/DeleteImageRequestDTO.java
  src/main/java/org/example/auctify/service/s3/FileUploadService.java
Labels: feat

#94 [FIX] 입찰 알림 API 수정
  src/main/java/org/example/auctify/controller/auction/GoodsController.java
  src/main/java/org/example/auctify/service/auction/GoodsService.java
Labels: bug

#98 [DOCS] 스웨거 문서 작성
  src/main/java/org/example/auctify/controller/chat/ChatRoomController.java
  src/main/java/org/example/auctify/controller/chat/ChatRoomControllerDocs.java
  src/main/java/org/example/auctify/controller/notification/NotificationController.java
  src/main/java/org/example/auctify/controller/notification/NotificationControllerDocs.java
  src/main/java/org/example/auctify/service/notification/NotificationService.java
Labels: documentation

#99 [Refactor] SSE 구독 API 변경
  src/main/java/org/example/auctify/controller/sse/SSEController.java
  src/main/java/org/example/auctify/controller/sse/SSEControllerDocs.java
  src/main/java/org/example/auctify/service/sse/SSEService.java
Labels: refactor
